version: "3.8"

services:
  prysmctl:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest" # Replace with the actual image name and version for prysmctl
    volumes:
      - ./data:/data  # Mount the host directory where you have the required files
    working_dir: /data
    command: >
      sh -c "./prysmctl testnet generate-genesis --fork=bellatrix --num-validators=64
      --output-ssz=genesis.ssz --chain-config-file=config.yml
      --geth-genesis-json-in=genesis.json --geth-genesis-json-out=genesis.json &&
      ./geth --datadir=gethdata init genesis.json &&
      ./geth --datadir=gethdata account import secret.json"

  geth:
    image: "ethereum/client-go:latest"  # Replace with the actual image name and version for Geth
    volumes:
      - ./data:/data  # Mount the host directory where you have the required files
      - gethdata:/gethdata  # Volume for persistent Geth data
    command: >
      sh -c "./geth --http --http.api=eth --http.addr=0.0.0.0 --authrpc.vhosts=* --datadir=/gethdata
      --allow-insecure-unlock --unlock=0x123463a4b065722e99115d6c222f267d9cabb524 console
      --syncmode=full --authrpc.jwtsecret=/data/jwt.hex --http.corsdomain=* --http.vhosts=*
      --password=/data/password.txt --nodiscover"
    ports:
      - "8545:8545"  # Map Geth HTTP-RPC port to the host

  beacon:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest" # Replace with the actual image name and version for the beacon chain
    volumes:
      - ./data:/data  # Mount the host directory where you have the required files
      - beacondata:/beacondata  # Volume for persistent beacon chain data
    command: >
      sh -c "./beacon-chain --datadir=/beacondata --min-sync-peers=0 --genesis-state=/data/genesis.ssz
      --chain-config-file=/data/config.yml --config-file=/data/config.yml --chain-id=32382
      --execution-endpoint=http://0.0.0.0:8551 --accept-terms-of-use --jwt-secret=/data/jwt.hex
      --rpc-host=0.0.0.0 --contract-deployment-block=0 --grpc-gateway-host=0.0.0.0
      --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524 --p2p-static-id"
    ports:
      - "8551:8551"  # Map Beacon chain HTTP-RPC port to the host

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"  # Replace with the actual image name and version for the validator client
    volumes:
      - ./data:/data  # Mount the host directory where you have the required files
      - validatordata:/validatordata  # Volume for persistent validator client data
    command: >
      sh -c "./validator --beacon-rpc-provider=beacon:4000 --datadir=/validatordata
      --accept-terms-of-use --interop-num-validators=64 --interop-start-index=0
      --chain-config-file=/data/config.yml"
    depends_on:
      - beacon
    networks:
      - prysmnet

networks:
  prysmnet:
    driver: bridge

volumes:
  gethdata:
  beacondata:
  validatordata:
